In [1]:
import numpy as np 
hello ='Hello World'
print(hello)


Hello World


In [2]:
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


In [22]:
arr2=np.array([[1,2],[3,4]])
print(arr2)

[[1 2]
 [3 4]]


In [12]:
arr2[1,1]

4

In [18]:
arr3=np.array([1, 2, 3, 4, 5, 6], ndmin=3)
print(arr3)
arr_float=np.array(arr3, dtype=float)
print(arr_float)
arr4=np.array([0,1,0,1])
arr_bool=np.array(arr4, dtype=bool)
print(arr_bool)

[[[1 2 3 4 5 6]]]
[[[ 1.  2.  3.  4.  5.  6.]]]
[False  True False  True]


In [19]:
print(arr3)
print(arr3.shape)

[[[1 2 3 4 5 6]]]
(1, 1, 6)


In [24]:
arr4=np.array(arr2)
print(arr4)
print(arr4.shape,'\n')
arr4.shape=(4,1)
print(arr4)
print(arr4.shape)


[[1 2]
 [3 4]]
(2, 2) 

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [27]:
arr5=arr2.reshape(4,1)
print(arr5)


[[1]
 [2]
 [3]
 [4]]


In [29]:
x=np.arange(1,21)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [35]:
y=np.linspace(1,20,num=10)
print(y)

[  1.           3.11111111   5.22222222   7.33333333   9.44444444
  11.55555556  13.66666667  15.77777778  17.88888889  20.        ]


In [37]:
xnum_arr=np.array([1,2,3,4]) 
print(xnum_arr)

[1 2 3 4]


In [41]:
a=np.arange(5,30,2)
print(a)
print(a[:5])
print(a[2:5])
print(a[7:])

[ 5  7  9 11 13 15 17 19 21 23 25 27 29]
[ 5  7  9 11 13]
[ 9 11 13]
[19 21 23 25 27 29]


In [42]:
print(a[::-1])

[29 27 25 23 21 19 17 15 13 11  9  7  5]


In [45]:
m=np.array([9,6,4,3])
n=np.array([3,5,6,7])
o=np.array([3,4,6,2])
print(np.vstack([m,n,o]))
print(np.hstack([m,n,o]))


[[9 6 4 3]
 [3 5 6 7]
 [3 4 6 2]]
[9 6 4 3 3 5 6 7 3 4 6 2]


In [46]:
r=np.arange(8)
print("r=",r)
print("r+10", r+10)

r= [0 1 2 3 4 5 6 7]
r+10 [10 11 12 13 14 15 16 17]


In [48]:
print(r)

[0 1 2 3 4 5 6 7]


In [60]:
X=np.random.randint( 1,10,100)
print(X)
print("mean= ", np.mean(X))
print("variance ", np.var(X))
print("standard deviation ", np.std(X))


[8 7 4 7 5 4 6 3 3 9 2 7 1 8 6 1 2 7 5 5 4 5 7 6 3 1 7 9 4 5 4 1 9 5 5 5 4
 7 8 6 1 6 5 3 1 2 5 7 5 4 2 6 7 4 3 9 9 2 7 6 6 3 7 2 9 2 1 9 9 8 7 4 4 7
 1 7 2 3 4 7 9 2 8 4 8 1 5 7 5 1 2 2 5 4 9 4 7 6 6 2]
mean=  4.98
variance  6.0196
standard deviation  2.45348731401
